name: Deploy 3-Tier Infra

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  AWS_REGION: us-east-2
  TF_IN_AUTOMATION: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configure AWS with ACCESS KEYS stored as repo secrets
      - name: Configure AWS credentials (access keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      # If your Terraform is in a subfolder, uncomment and set the path,
      # then add -chdir=${{ env.TF_WORKING_DIR }} to the TF commands below.
      # - name: Set working directory
      #   run: echo "TF_WORKING_DIR=infra" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init -input=false
        # run: terraform -chdir=${{ env.TF_WORKING_DIR }} init -input=false

      - name: Terraform Validate
        run: terraform validate
        # run: terraform -chdir=${{ env.TF_WORKING_DIR }} validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false
        # run: terraform -chdir=${{ env.TF_WORKING_DIR }} plan -out=tfplan -input=false

      - name: Terraform Apply (main only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan
        # run: terraform -chdir=${{ env.TF_WORKING_DIR }} apply -input=false -auto-approve tfplan
